num=str(input("Digite um numero entre 0 e 9999: ")).zfill(4)
print("Milhar: {}".format(num[0]))
print("Centena: {}".format(num[1]))
print("Dezena: {}".format(num[2]))
print("Unidade: {}".format(num[3]))